upgrade:
  name: upgrade-nova
  image: nova-api
  steps:
    - name: db-sync
      command: nova-manage db sync
      files:
        - nova.conf
    - name: api-db-sync
      command: nova-manage api_db sync
      files:
        - nova.conf
    - name: kill-control-plane
      type: kill-services
      services:
        - nova-api
        - nova-conductor
        - nova-consoleauth
        - nova-novncproxy
        - nova-scheduler
    - name: roll-conductor
      type: rolling-upgrade
      services: [nova-conductor]
    - name: roll-other
      type: rolling-upgrade
      services:
        - nova-consoleauth
        - nova-novncproxy
        - nova-scheduler
    - name: roll-api
      type: rolling-upgrade
      services: [nova-api]
    - name: roll-compute
      type: rolling-upgrade
      services: [nova-compute]
    - name: roll-libvirt
      type: rolling-upgrade
      services: [nova-libvirt]
    - name: nova-db-migrations
      command: nova-manage db online_data_migrations
      files:
        - nova.conf
files:
  nova.conf:
    path: /etc/nova/nova.conf
    content: nova.conf.j2
    perm: "0600"
