FROM {{ image_spec("nova-base") }}
MAINTAINER {{ maintainer }}

COPY {{ render('sources.list.debian.j2') }} /etc/apt/sources.list.d/testing.list

# qemu-system-x86 depends on libgtk-3-0 libvte-2.91-0 that are provided
# by testing repository and doesn't exist in jessie-backports, so we need
# to install them before installing qemu-kvm from jessie-backports

RUN apt-get update \
    && apt-get -y install libgtk-3-0 libvte-2.91-0 \
    && apt-get -y install -t jessie-backports --no-install-recommends \
        qemu-kvm \
        qemu-block-extra \
    && apt-get -y install libvirt-daemon -t testing --no-install-recommends \
        libvirt-bin \
    && apt-get -y install --no-install-recommends \
        ceph-common \
        python-ceph \
        python-rados \
        libvirt-bin \
        dmidecode \
        pm-utils \
        ebtables \
        xen-utils-4.4 \
    && apt-get clean \
    && mkdir -p /etc/ceph \
    && rm -f /etc/libvirt/qemu/networks/default.xml /etc/libvirt/qemu/networks/autostart/default.xml \
    && usermod -a -G libvirt nova \
    && ln -s /usr/lib/python2.7/dist-packages/rados.so /var/lib/microservices/venv/local/lib/python2.7/site-packages/rados.so \
    && ln -s /usr/lib/python2.7/dist-packages/rados-0.egg-info /var/lib/microservices/venv/local/lib/python2.7/site-packages/rados-0.egg-info \
    && ln -s /usr/lib/python2.7/dist-packages/rbd-0.egg-info /var/lib/microservices/venv/local/lib/python2.7/site-packages/rbd-0.egg-info \
    && ln -s /usr/lib/python2.7/dist-packages/rbd.so /var/lib/microservices/venv/local/lib/python2.7/site-packages/rbd.so
