FROM {{ namespace }}/nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

RUN apt-get -y install --no-install-recommends \
        ceph-common \
        libvirt-bin \
        dmidecode \
        pm-utils \
        qemu-kvm \
        qemu-block-extra \
        ebtables \
        xen-utils-4.4 \
    && apt-get clean \
    && mkdir -p /etc/ceph \
    && rm -f /etc/libvirt/qemu/networks/default.xml /etc/libvirt/qemu/networks/autostart/default.xml \
    && usermod -a -G libvirt nova
