FROM {{ namespace }}/openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

RUN curl -o nova-{{ branch }}.tar.gz http://tarballs.openstack.org/nova/nova-{{ branch }}.tar.gz \
    && tar -zxvf nova-{{ branch }}.tar.gz

RUN apt-get install -y --no-install-recommends \
        bridge-utils \
        openvswitch-switch \
        iptables \
        ebtables \
        dnsmasq \
        openssh-client \
    && apt-get clean

RUN mv nova*/ nova-{{ branch }}/ \
    &&  ln -s nova-{{ branch }}/ /nova \
    && useradd --user-group --create-home --home-dir /var/lib/nova nova \
    && chmod 755 /var/lib/nova \
    && /var/lib/microservices/venv/bin/pip --no-cache-dir install --upgrade -c nova-{{ branch }}/requirements.txt /nova \
    && mkdir -p /etc/nova /var/lib/nova /var/log/nova \
    && cp -r /nova/etc/nova/* /etc/nova/ \
    && chown -R nova: /etc/nova /var/lib/nova /var/log/nova \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/microservices/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/nova/rootwrap.conf

COPY nova_sudoers /etc/sudoers.d/nova_sudoers
RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/nova_sudoers

RUN usermod -a -G microservices nova
