FROM {{ image_spec("openstack-base") }}
MAINTAINER {{ maintainer }}

COPY {{ render('sources.list.debian.j2') }} /etc/apt/sources.list.d/ceph.list
RUN apt-key adv --recv-keys --keyserver {{ url.ceph.debian.keyserver }} \
    {{ url.ceph.debian.keyid }} \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        bridge-utils \
        openvswitch-switch \
        iptables \
        ebtables \
        dnsmasq \
        openssh-client \
    && apt-get clean

{{ copy_sources("openstack/nova", "/nova") }}

RUN useradd --user-group --create-home --home-dir /var/lib/nova nova \
    && chmod 755 /var/lib/nova \
    && /var/lib/microservices/venv/bin/pip install /nova \
    && mkdir -p /etc/nova /var/lib/nova /var/log/nova \
    && cp -r /nova/etc/nova/* /etc/nova/ \
    && chown -R nova: /etc/nova /var/lib/nova /var/log/nova \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/microservices/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/nova/rootwrap.conf

COPY nova_sudoers /etc/sudoers.d/nova_sudoers
RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/nova_sudoers \
    && usermod -a -G microservices nova
