FROM {{ namespace }}/openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

RUN apt-get install -y --no-install-recommends \
        bridge-utils \
        openvswitch-switch \
        iptables \
        ebtables \
        dnsmasq \
        openssh-client \
    && apt-get clean

{{ copy_sources("openstack/nova", "/nova") }}

RUN useradd --user-group --create-home --home-dir /var/lib/nova nova \
    && chmod 755 /var/lib/nova \
    && /var/lib/microservices/venv/bin/pip install --upgrade /nova \
    && mkdir -p /etc/nova /var/lib/nova /var/log/nova \
    && cp -r /nova/etc/nova/* /etc/nova/ \
    && chown -R nova: /etc/nova /var/lib/nova /var/log/nova \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/microservices/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/nova/rootwrap.conf

COPY nova_sudoers /etc/sudoers.d/nova_sudoers
RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/nova_sudoers

RUN usermod -a -G microservices nova
